services:
  postgres:
    image: postgres:15
    container_name: strapi-postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-net

  strapi:
    image: onkarlonkar9/new-strapi-v1
    container_name: strapi-app
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi_password
      HOST: 0.0.0.0
      PORT: 1337
    ports:
      - "1337:1337"
    networks:
      - strapi-net

  nginx:
    image: nginx:latest
    container_name: jarvis_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge

volumes:
  postgres-data:

